### ISSUE TITLE
How to get access to MuseNet?

### ISSUE THREAD

**Issue by aviv-or** [stevenwaterman/musetree#102]
Not directly related to your project, but how can this project be replicated if the API is no longer available? I tried contacting OpenAI and got no response.

Is the API still publicly?

**Comment by stevenwaterman** [comment]
The API was never public, I reverse engineered it based on their [official tool](https://openai.com/blog/musenet/). They're not thrilled about it, but tolerate it. You can see the MuseNet code [here](https://github.com/stevenwaterman/musetree/tree/master/src/bridge)

**Comment by aviv-or** [comment]
Got it :)
Thanks for the quick answer!
