### ISSUE TITLE
[feature request] Option to use MuseNet mp3 instead of synth when previewing the track

### ISSUE THREAD

**Issue by mbartlett21** [stevenwaterman/musetree#105]
The title should say it all.

**Comment by stevenwaterman** [comment]
You can always use https://stevenwaterman.uk/musetree-legacy/

I don't plan on supporting the MuseNet mp3 because it prevents us from doing any post-processing on the midis that it sends back. I know the synth is kinda crap, I just never got around to improving it

**Comment by mbartlett21** [comment]
Ok. I didn't realise about the legacy version :)

And this is probably then covered by one of the issues around synths, so this issue can close then.
