### ISSUE TITLE
Improve Color Scheme

### ISSUE THREAD

**Issue by stevenwaterman** [stevenwaterman/musetree#2]
The current colors are a bit painful and are literally the first ones that I tried

**Comment by farfromsubtle** [comment]
haha, I actually don't mind them. Although I will say the white window on the right for the generator is quite harsh for my dark-mode loving eyes. Not a deal breaker though.

On a side note: I much preferred the lines connecting each circle in the previous version. For larger branching projects I am finding it more difficult to keep track of what goes where. Could this perhaps be a toggle?

**Comment by stevenwaterman** [comment]
Yep, I do intend to improve the lines in tree view. Previously I was using a library called D3, but that didn't work with the way I stored the tree. The current lines were just meant to be a stop-gap measure while I was working on v2 and just kept getting put off. I'll open a specific ticket for that: https://github.com/stevenwaterman/musetree/issues/39 . You're right that the options column should be recoloured, ticket for that is https://github.com/stevenwaterman/musetree/issues/40

Regarding the colour scheme, eventually i'll let you customise it with your own colours (and probably change the defaults at that point).

**Comment by stevenwaterman** [comment]
Fixed in v2.1.7
