### ISSUE TITLE
Options column should be dark themed

### ISSUE THREAD

**Issue by stevenwaterman** [stevenwaterman/musetree#40]
The options panel on the far right of the screen is black-on-white while everything else is white-on-black. It should be changed to match.

**Comment by stevenwaterman** [comment]
Fixed in v2.1.5

**Comment by farfromsubtle** [comment]
I am not used to software improving at such a rapid rate. I love seeing new improvements everytime I log it! The new color scheme looks great! You've got a good eye for aesthetics!

**Comment by stevenwaterman** [comment]
I'm currently furloughed at work so this is basically my full time job :laughing: I livestream my work on it Mon-Fri 2-6pm if you fancy coming along and chating/giving suggestions! twitch.tv/stevenwaterman

p.s. I have a terrible eye for aesthetics, the colour scheme is completely stolen and I just copied my IDE:
![image](https://user-images.githubusercontent.com/23333247/82736861-842ac380-9d24-11ea-8a65-3979ef894021.png)
