### ISSUE TITLE
Performance issues when selecting section on large tree

### ISSUE THREAD

**Issue by stevenwaterman** [stevenwaterman/musetree#49]
When selecting a section on a large tree, the app can hang for 30+ seconds. A first look in the profiler suggests that the stores are triggering O(n) updates where n is the tree depth. They should only trigger 1.

**Comment by stevenwaterman** [comment]
This is drastically improved in v2.14.2 - Rendering performance is still bad but should improve with https://github.com/stevenwaterman/musetree/issues/57

**Comment by farfromsubtle** [comment]
If by rendering you mean the drawn notes? I find the preformance to be quite good. Probably varies form machine to machine?

**Comment by stevenwaterman** [comment]
Yeah - When you click a node in the tree vis 2 things happen - figuring out what the track should be (i.e. joining all the nodes in the path from root to the one you clicked), then rendering it on the screen. Looking at it with a profiler, the data part used to be the slow bit but now it's improved enough that rendering is the limiting factor.

It's certainly usable, but it could be near-instant

**Comment by stevenwaterman** [comment]
Render performance is massively improved as of 2.15.2 - It should be more than usable now. The bottleneck is now the data section again
