### ISSUE TITLE
Determine the correct max value for `max length`

### ISSUE THREAD

**Issue by stevenwaterman** [stevenwaterman/musetree#59]
At the current max value of 3000, I have never successfully got a response from MuseNet. The max value should be decreased until it's still *possible* to get a response (even if it fails 90% of the time)

**Comment by stevenwaterman** [comment]
I just got a success at 3000. Maybe it should be increased?

**Comment by stevenwaterman** [comment]
3000 seems like the max

**Comment by farfromsubtle** [comment]
Sorry I should have chimed in on this.

Musenet is super finicky but in the last week it has been quite responsive. 3000 has been my default without any issues. I think the he Jukebox release gave OpenAI a lot of attention earlier in the month which caused too many requests to their other stuff like musenet?

**Comment by stevenwaterman** [comment]
Since you've had repeated success with 3000, I'll reopen this. I will increase the max to 5000 and amend the tooltip to mention that values below 3000 are known to work. I assume you're right about the failed requests being due to Jukebox - but there's not enough information to say either way.

**Comment by stevenwaterman** [comment]
Upped to 5000 in 2.15.3

**Comment by farfromsubtle** [comment]
So I have been using 5000 with huge success which is great BUT...

I have yet to see the model recall any theme further back than about 2000. I am going to keep notes on the most distant repeated motif but I have a suspicion that there is an unpublished maximum  number and it potentially doesn't matter what we request?

So far my best bet for returning musenet to a chorus that ui want repeated has been to paste it in with the add midi feature on musetree.
