### ISSUE TITLE
Add a progress bar to the loading modal

### ISSUE THREAD

**Issue by stevenwaterman** [stevenwaterman/musetree#61]
Just a simple `number of sections complete/number of sections`

**Comment by stevenwaterman** [comment]
Added 2.12.0

**Comment by farfromsubtle** [comment]
Again I don't know where to put comments so I will just toss one one a closed issue. The improvements have been incredible. I can't even keep up with the new changes. Everytime I jump back in something has gotten better and I just went back to my monster tree and clicking around the branches with ease! Amazing work!

**Comment by stevenwaterman** [comment]
Your comment has made my day :) Thanks for being so involved and giving feedback + suggestions! It's incredibly motivating to know that my little personal project is useful for other people, and your feedback on GitHub makes it much easier to prioritise + know I'm working on the right thing

**Comment by stevenwaterman** [comment]
Re: comments + general feedback - I can open an issue that's just for that? Alternatively you've got my email address and i'm happy to chat, or come say hi on twitch!
