### ISSUE TITLE
Load More and Right Click

### ISSUE THREAD

**Issue by farfromsubtle** [stevenwaterman/musetree#62]
From a new user's perspective, the lack of a "load more" button might be a bit confusing as it is hidden behind the contextual right click.

From a power-user's perspective, the addition of a drop down menu click to load more is a bit cumbersome and the removal of right-click delete will make tree trimming on large projects a bigger chore.

I understand what you are going for in making a more streamlined interface though. Maybe on left click the contextual menu appears automatically so it does not require an extra right click after listening. That would also free up right click to delete again.

ctrl-click load more: I didn't know that was a thing because on mac ctrl-click IS right click. Now that I know that was a feature I want it back too! That would really speed up the workflow!

This probably isn't an issue, but I don't know where else to put stuff like this on github. I also hate for this to seem like complaining since I am so greatful for the work being done on this incredible projects! Just giving my feedback!

**Comment by stevenwaterman** [comment]
I'm aware of the issues with the new flow for both new users and power users.

For new users, I'll have something which explains that you need to right-click a tree vis node to start. Maybe something as simple as a label that says `click me to start` if it's your first time using the app.

For power users, i'm adding keyboard shortcuts. I'm started working on that yesterday and aim to have it implemented today. At first, it will just be keyboard shortcuts to select an option in the context modal, but eventually you'll just be able to hover a node and press the key without having to open the modal.

**Comment by stevenwaterman** [comment]
Keyboard shortcuts supported in 2.10.1 - Both when hovering on a node and after right-clicking a node. The key you need to press is the first (underlined) letter in the context modal.
I will open a separate issue for first-time user friendliness

**Comment by stevenwaterman** [comment]
As promised, https://github.com/stevenwaterman/musetree/issues/65

**Comment by farfromsubtle** [comment]
Wow those keyboard shortcuts are a huge help! That basically solves any issues I had with the changes.
