### ISSUE TITLE
Cancel Load Causes Loading Hang

### ISSUE THREAD

**Issue by farfromsubtle** [stevenwaterman/musetree#63]
If you press the load button and subsequently cancel loading an mst file (this has happened a few times to me when I mistakenly hit load instead of "load more" the interface with then hang on the "loading..." wheel indefinitely.

**Comment by stevenwaterman** [comment]
I thought I'd fixed that in 2.9.0: https://github.com/stevenwaterman/musetree/commit/027b86292249b2dc8bb831a78cc7f88e728d8559#diff-2b6797ab6f6e238f1369975f3aa99975

So you click load, the modal pops up and you click cancel, and the loading spinner is there forever? I just tried and that doesn't happen for me - maybe it's a mac vs linux thing?

**Comment by farfromsubtle** [comment]
I noticed it doesn't happen on fresh trees? The project it last happened on also had a large midi loaded from another tree after the root. Maybe that has something to do with it?

**Comment by stevenwaterman** [comment]
Cool, i'll look into that shortly and try to replicate it

**Comment by stevenwaterman** [comment]
This is fixed v2.11.2 - I was checking if the file list returned was null, but turned out sometimes it's non-null but empty. Now checking for both null and empty
