### ISSUE TITLE
Hide Instruments in Timeline

### ISSUE THREAD

**Issue by farfromsubtle** [stevenwaterman/musetree#68]
Sometimes finding a repeating motif during composition is easier by just looking at the timeline instead of listening for it. It would be even easier if the user could isolate the leading instrument (piano or guitar usually) to help identify these patterns. In general this could also declutter complicated compositions on the timeline.

I picture potentially checkboxes to show/hide each instrument.

**Comment by stevenwaterman** [comment]
This would go nicely with the custom colour schemes ticket. Actually doing it isn't hard, but I'm struggling to think of where to put the option. I'm imagining a `display settings` modal, but not sure how that should be opened. Any ideas?

**Comment by stevenwaterman** [comment]
Added 2.17.0
