### ISSUE TITLE
Info: Taking a short break

### ISSUE THREAD

**Issue by stevenwaterman** [stevenwaterman/musetree#74]
Hi all. Couldn't think of where else to put this so I'm leaving it as a pinned GitHub issue. I'm taking a short (couple of weeks) break from MuseTree to work on other projects including an upcoming conference talk I'm giving.

I'll probably be still be around to answer questions and give clarity on any GitHub issues, but you probably won't see any new features for the next couple of weeks. If there's critical bugs, I'll still look at them.

**Comment by farfromsubtle** [comment]
Thanks for all your work and good luck at your conference!

**Comment by stevenwaterman** [comment]
Back now, restarting work on MuseTree. I'm full-time on this until tuesday, after which I'm back at work so it will be evenings and weekends only!
