### ISSUE TITLE
Occasional Note Bursts in new Segments

### ISSUE THREAD

**Issue by farfromsubtle** [stevenwaterman/musetree#76]
Occasionally a new segments will come with a big blast of notes that are (thankfully) not present on the exported midi and hopefully not on the encoding. These bursts are also present on the musetree audio rendering but not the musenet. 

In this particular case, it may be worth noting that the museNET audio had a some run-on notes particularily from the wind section. Could this be a side effect of that muse-net/muse-tree disparity?

I am working around them by trying to ignore them and just focus on the resulting midi file. It doesn't seem like the model is being reinforced to produce these from what I can tell.

<img width="551" alt="Screen Shot 2020-06-07 at 16 07 00" src="https://user-images.githubusercontent.com/38600758/83962595-8d499200-a8d9-11ea-91cd-486e71ea39ce.png">

**Comment by stevenwaterman** [comment]
I think this is fixed as of v2.20.0 - Let me know if it keeps happening for you!
