### ISSUE TITLE
some notes go on extrememly long

### ISSUE THREAD

**Issue by cringegaming64** [stevenwaterman/musetree#79]
i noticed that about 25% of the compositions i make, some notes would just keep on going untill it was played again by the same instrument and same note at which point fixes it self. this is not a problem with midi but it is annoying to hear a constant 8 bit square while trying to listen to the music in  mustree

**Comment by stevenwaterman** [comment]
Do you have an example of this happening? This was a known bug in the past, but was supposed to have been fixed :(

**Comment by stevenwaterman** [comment]
Closing as unable to reproduce. Let me know if you have a reproducible example :)
