### ISSUE TITLE
correct midi notes: overlaps, too long, too short

### ISSUE THREAD

**Issue by FreddieM007** [stevenwaterman/musetree#82]
I don't know if this has already been addressed in MuseTree or not:
1) In working with MuseNet output midi files, I noticed that MuseNet often generates overlapping notes. For the midi standard this makes no sense. Although it does not affect playback directly it makes it harder to postprocess these files. I always remove overlapping notes in a DAW with a macro but it would be great if your tool could fix this automatically.

2) MuseNet sometimes generates too long notes: Reading through the issue tracker this seems already been solved but I wanted to mention it anyway.

3) MuseNet sometimes generates too short notes: These notes should not be removed since they get played accurately. Instead, a heuristic that sets them to a minimum length (automatically determined?)  would make it better to post-process.

4) MuseNet often has no space between subsequent playing of the same note. This is physically impossible. All instruments need a tiny gap (automatically determined?) between hitting or playing the same note twice.

Algorithmically, the corrections should be computed in this order: 3), 1), 4), 2) to ensure no damage by the corrections.

**Comment by stevenwaterman** [comment]
1 and 2 should be solved by the post-processing that is already implemented in MuseTree. 3 and 4 are good points, and I will add them as (configurable, default-off) stages in the processing pipeline

**Comment by FreddieM007** [comment]
Thank you!

**Comment by FreddieM007** [comment]
Sorry, pushed the wrong button

**Comment by stevenwaterman** [comment]
Fixed in v2.20.0
