### ISSUE TITLE
is it possible to make an executable?

### ISSUE THREAD

**Issue by rafaelkb** [stevenwaterman/musetree#90]
I am having some connection issues since i live in another country.
 Is it possible to make an executable version of musetree?

**Comment by s-a** [comment]
you can do it yourself using electron  by github

**Comment by stevenwaterman** [comment]
Since MuseTree uses the MuseNet api, it will never work fully offline. There has been some discussion of creating an in-brower ML system but I don't expect that to ever actually happen. Going to close this issue - sorry!
