### ISSUE TITLE
Add ability to control how many branches you request

### ISSUE THREAD

**Issue by austincap** [stevenwaterman/musetree#96]
Instead of only 4, allow 1 to 8 branches to be generated.

**Comment by stevenwaterman** [comment]
Thanks for opening the issue. The reason that musetree requests 4 branches at a time is because the underlying musenet API will always send 4 branches in response. I could add the option to request 8 at a time (by sending 2 requests), but this would increase the load on musenet which I'm hesitant to do.

Why do you need this, and can you just send 2 requests instead?

**Comment by austincap** [comment]
My thought was if it only generated 2 branches per request then they'd generate twice as fast, allowing for slightly more fluid comproducing*. I'd even use single branch generation cause I often find myself lowering the temperature and keeping the AI in a particular groove for a while just to see where it ends up. Furthermore being able to reduce the number of branches generated per request just makes the whole tree less unwieldy, although I guess manual pruning is already an option. 

Now that I think about it, what would be really handy is an option to autoprune the 4 branches just generated and replace them with 4 newly generated branches, rather than keep tacking an additional 4 branches on. If I'm making a second request, it's always because I don't like any of what I got from the first request. Rather than append, replace.

Regardless, if the API always sends 4 branches in response then I guess nevermind. I'll close this cause it's not a big deal but please consider my "new requests replace branches rather than append to them" idea.

*A portmanteau of composing and producing. Musenet is doing the _composing_ while the user functions like a _producer_ in the mixing booth telling the composer what is shit and what is good. Someone's gotta come up with a verb to describe this new method of generating music cause as far as I know there isn't one yet.
