### ISSUE TITLE
Playing only piano, strings and winds.

### ISSUE THREAD

**Issue by MrChuw** [stevenwaterman/musetree#97]
The musetree player is playing only the piano, strings and winds. Simple as that, I tried to run it on my pc (windows) to test it and on my raspberry 3b+ and both only play these 3.

**Comment by stevenwaterman** [comment]
Are you saying that the track view on the left shows, for example, drum notes, but that when you play the song you can't hear them? Or are you saying that it never actually puts any drum notes in the song?

I just tried it on my end, first requesting a song with just drums, and then requesting a song with just harp. In both cases it worked fine.

**Comment by MrChuw** [comment]
Sorry, before when I first tried bass, drums, guitar and harp they were muted in musetree player and export, but now they work again. It was probably something wrong with my browser/pc.
